### ISSUE TITLE
Alpha Tauri stats issue

### ISSUE THREAD

**Issue by hotlapmode** [jose-donato/hotlapmode.app#4]
When selecting 2022>Teams>Alpha Tauri on the app, the stats (points, wins, position) from Alpha Tauri do not appear. 
From iOS, Chrome (PWA app)

![hotlapmode app - hotlapmode 1_23_2023 4_15_27 PM](https://user-images.githubusercontent.com/67686869/214077579-2eccebdd-2858-4543-953f-a877d286de20.png)

**Comment by jose-donato** [comment]
i think the problem is that the name should be alphatauri and not alpha tauri on the team details

**Comment by jose-donato** [comment]
this was it.
fixed
