### ISSUE TITLE
Information page

### ISSUE THREAD

**Issue by hotlapmode** [jose-donato/hotlapmode.app#5]
_Multiple requests have come through asking to specify what exactly every criteria means and how we reach those numbers, this is an explanation for every criteria featured in the website so far_

Media rating: media rating is an average between the ratings of three of the main Formula 1 related websites at the moment, Auto motor und Sport, CRASHnet and Autosport. 

HLM Rating: specific rating given out by ourselves, mainly focusing on the performance of a driver race by race and leaving the final results as a secondary criteria of evaluation. In this way drivers from top teams and midfield drivers are closer together.

Quali Pace: Qualifying pace is often not calculated properly, because of the many variables that are easy to take out of the equation. First of all, the main goal is to compare teammates: lap times for each driver are taken from the last session (Q1, Q2, Q3) where both teammates competed in order to remove track evolution as a variable. This is why non-teammate comparisons are sometimes not entirely accurate.
Qualifying pace for teams is based on the best mini sectors from the fastest driver for each team every weekend.

Quali H2H: Head to Head between teammates is fairly simple, although the numbers you see don’t consider sessions where one of the two had a major issue with the car, or had a grid penalty and thus did not express their full potential in Qualifying. Between non-teammates the system is automated and gives the point to the faster driver of the two.

Race pace: For top teams it is calculated accurately by ourselves removing outlier laps and giving a very accurate measurement of every drivers’ and teams’ pace. When considering the midfield, FastF1 is used to calculate race pace, an automated system which is still accurate and reliable but not as precise as the system used for top teams for time reasons. 
Pace for the Monaco Grand Prix is not considered due to traffic playing a significant role in the pace that every driver can express.
Team race pace considers the best race pace value between the two drivers

Race H2H: Similarly to Qualifying H2H, this is fairly simple, but major outliers are taken out. Unfortunately race H2H isn’t the most reliable way to compare teammates since penalties, strategies, setups and more can’t be considered. Between non-teammates the system is automated and gives the point to the faster driver of the two.

**Comment by jose-donato** [comment]
@joaodunas can take it
